Feature/authentication
roommate6/team-pst pull request #2
Opened 2023-12-18 12:47 UTC by tudorp9k

Backend authentication with Microsoft Identity.

2023-12-19 07:03 UTC, Paul-Podoleanu commented
Aprob :3

2023-12-19 18:03 UTC, roommate6 requested changes
Tested the register api. It works. Good job! But before merging with the main, check the feedback on some lines.

2023-12-19 18:03 UTC, roommate6 commented on back-end/YummyGen/YummyGen.Application/AuthenticationService.cs
> +        public async Task<UserDto> Register(RegisterDto userDto)
rename userDto with registerDto. For the loginDto you've done that, but for the register, not...

2023-12-19 18:03 UTC, roommate6 commented on back-end/YummyGen/YummyGenAPI/Startup.cs
> +            builder.Services.AddIdentity<User, IdentityRole>(options =>
Good job. I never knew that you can use such a powerful tool for passwords. I will consider now using this in feature projects. Ty

2023-12-19 18:59 UTC, tudorp9k commented on back-end/YummyGen/YummyGen.Application/AuthenticationService.cs
> +        public async Task<UserDto> Register(RegisterDto userDto)
Updated 👍

2023-12-20 06:35 UTC, roommate6 approved these changes
now everything is good

2023-12-20 06:36 UTC, merged